apiVersion: 1

datasources:
- name: chameleon
  type: postgres
  url: chameleon_postgres:9999
  access: proxy
  user: changeme027a088931d22
  password: changeme0f40773877963
  database: chameleon
  basicAuth: false
  isDefault: true
  jsonData:
     sslmode: disable
  version: 1
  editable: true
